src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\CategoryRepository;
use App\Repository\FortuneCookieRepository;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 20)]
    private ?string $iconKey = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: FortuneCookie::class, fetch: 'EXTRA_LAZY')]
    private Collection $fortuneCookies;

    public function __construct()
    {
        $this->fortuneCookies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIconKey(): ?string
    {
        return $this->iconKey;
    }

    public function setIconKey(string $iconKey): self
    {
        $this->iconKey = $iconKey;

        return $this;
    }

    /**
     * @return Collection<int, FortuneCookie>
     */
    public function getFortuneCookies(): Collection
    {
        return $this->fortuneCookies;
    }


   /**
    * @return Collection<int, FortuneCookie>
    */
    public function getFortuneCookiesStillInProduction(): Collection
    {
        $criteria = FortuneCookieRepository::createFortuneCookieStillInProductionCriteria();

        return $this->fortuneCookies->matching($criteria);


    }


    public function addFortuneCookie(FortuneCookie $fortuneCookie): self
    {
        if (!$this->fortuneCookies->contains($fortuneCookie)) {
            $this->fortuneCookies->add($fortuneCookie);
            $fortuneCookie->setCategory($this);
        }

        return $this;
    }

    public function removeFortuneCookie(FortuneCookie $fortuneCookie): self
    {
        if ($this->fortuneCookies->removeElement($fortuneCookie)) {
            // set the owning side to null (unless already changed)
            if ($fortuneCookie->getCategory() === $this) {
                $fortuneCookie->setCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/FortuneCookie.php
<?php

namespace App\Entity;

use App\Repository\FortuneCookieRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FortuneCookieRepository::class)]
class FortuneCookie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $fortune = null;

    #[ORM\Column]
    private ?int $numberPrinted = null;

    #[ORM\Column]
    private bool $discontinued = false;

    #[ORM\Column]
    private \DateTimeImmutable $createdAt;

    #[ORM\ManyToOne(inversedBy: 'fortuneCookies')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    /**
     * @param \DateTimeImmutable|null $createdAt
     */
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFortune(): ?string
    {
        return $this->fortune;
    }

    public function setFortune(string $fortune): self
    {
        $this->fortune = $fortune;

        return $this;
    }

    public function getNumberPrinted(): ?int
    {
        return $this->numberPrinted;
    }

    public function setNumberPrinted(int $numberPrinted): self
    {
        $this->numberPrinted = $numberPrinted;

        return $this;
    }

    public function isDiscontinued(): bool
    {
        return $this->discontinued;
    }

    public function setDiscontinued(bool $discontinued): self
    {
        $this->discontinued = $discontinued;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/FortuneController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Repository\CategoryRepository;
use App\Repository\FortuneCookieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FortuneController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function index(Request $request, CategoryRepository $categoryRepository, EntityManagerInterface $entityManagerInterface): Response
    {

        $entityManagerInterface->getFilters()
            ->enable('fortuneCookie_discontinued')
            ->setParameter('discontinued', false);

        $searchTerm = $request->query->get('q');
        if($searchTerm){
            $categories = $categoryRepository->search($searchTerm);
        }else{
            $categories = $categoryRepository->findAllOrdered();
        }


        return $this->render('fortune/homepage.html.twig',[
            'categories' => $categories
        ]);
    }

    #[Route('/category/{id}', name: 'app_category_show')]
    public function showCategory(int $id, CategoryRepository $categoryRepository, FortuneCookieRepository $fortuneCookieRepository): Response
    {

        $category = $categoryRepository->findWithFortunesJoin($id);

        if(!$category){
            throw $this->createNotFoundException('Category not found');
        }
        $stats = $fortuneCookieRepository->countByNumberPrintedForCategory($category);


        return $this->render('fortune/showCategory.html.twig',[
            'category' => $category,
            'fortunesPrinted' => $stats->fortunesPrinted,
            'fortunesAverage' => $stats->fortunesAverage,
            'categoryName' => $stats->categoryName,

        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Fortune Queries{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body class="flex flex-col min-h-screen">
        <nav class="border-gray-200 px-4 py-5 bg-gray-900">
            <div class="container flex flex-wrap items-center justify-between mx-auto">
                <a href="{{ path('app_homepage') }}" class="flex items-center">
                    <img src={{ asset('build/images/fortune-logo.png') }} class="h-9 mr-3" alt="Fortune Queries Logo"/>
                    <span class="self-center text-xl font-semibold whitespace-nowrap text-white">Fortune Queries</span>
                </a>
                <div class="flex">
                    <div class="relative">
                        <form action="{{ path('app_homepage') }}">
                            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                <svg class="w-5 h-5 text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
                                <span class="sr-only">Search icon</span>
                            </div>
                            <input type="text" id="search-navbar" name="q" value="{{ app.request.query.get('q') }}" placeholder="Search..." class="block w-full p-2 pl-10 text-sm border rounded-lg bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500">
                        </form>
                    </div>
                </div>
            </div>
        </nav>
        {% block body %}{% endblock %}
        <footer class="mt-auto bg-slate-100">
            <div class="p-5 flex justify-between">
                <p>Brought to you with <i class="fas fa-heart text-red-600"></i> from <a class="underline hover:text-blue-600" href="https://symfonycasts.com/">SymfonyCasts</a></p>
                <div class="text-lg">
                    <a class="text-gray-700 hover:text-gray-900" href="https://twitter.com/SymfonyCasts"><i class="fa-brands fa-twitter"></i></a>
                    <a class="text-gray-700 hover:text-gray-900" href="https://www.facebook.com/SymfonyCasts"><i class="fa-brands fa-facebook"></i></a>
                    <a class="text-gray-700 hover:text-gray-900" href="https://github.com/SymfonyCasts"><i class="fa-brands fa-github"></i></a>
                </div>
            </div>
        </footer>
    </body>
</html>

templates/fortune/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1 class="text-center my-8 text-2xl text-slate-800 font-bold">Query for your Fortune</h1>
<p class="text-center">Review categories for available cookie fortunes</p>
<div class="xl:container xl:mx-auto grid grid-cols-2 gap-6 px-10 mt-8 mb-10">
    {% for categoryData in categories %}
    {% set category = categoryData[0]  %}
        <a class="bg-orange-400 hover:bg-orange-500 text-white text-center rounded-full p-4" href="{{ path('app_category_show', {'id':  category.id}) }}">
            <span class="fa {{ category.iconKey }}"></span> <span class="font-bold text-lg">{{ category.name }}</span>  ({{ categoryData.fortuneCookiesTotal }})
        </a>
    {% else %}
        <h3>Hmm... there don't seem to be any fortunes</h3>
    {% endfor %}
</div>
{% endblock %}

templates/fortune/showCategory.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    
        
<h1 class="text-3xl p-5 text-center my-4 font-semibold"><span class="fa {{ category.iconKey }}"></span> {{ categoryName }} Fortunes</h1>
<div class="flex justify-center mb-16 px-4">
    <div>
        <table class="table-auto border mb-6">
            <thead class="bg-slate-500 text-white">
                <tr>
                    <th class="border p-4">
                        Fortunes
                    </th>
                    <th class="border p-4">
                        Print History ({{ fortunesPrinted|number_format }} total, {{ fortunesAverage|number_format }} average)
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for fortuneCookie in category.fortuneCookiesStillInProduction %}
                <tr class="hover:bg-slate-200">
                    <td class="border p-4">
                        {{ fortuneCookie.fortune }}
                    </td>
                    <td class="border p-4">
                        {{ fortuneCookie.numberPrinted }} printed since {{ fortuneCookie.createdAt|date('M jS Y') }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a class="text-slate-700 hover:text-slate-900 font-semibold" href="{{ path('app_homepage') }}"><i class="fa fa-angle-double-left"></i> Back to Fortune Categories</a>
    </div>
</div>
    
        
    
{% endblock %}